RiHotel/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from booking import views

router = routers.DefaultRouter()
router.register(r'subcategories', views.RoomSubCategoryViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('dashboard/', include('dashboard.urls')),
]+static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:subcategory_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:subcategory_id>/', views.cart_remove, name='cart_remove'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    room_quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from booking.models import RoomCategory, RoomSubCategory, RoomCategory
from .cart import Cart
from .forms import CartAddProductForm

categories = RoomCategory.objects.all()

@require_POST
def cart_add(request, subcategory_id):
    cart = Cart(request)
    subcategory = get_object_or_404(RoomSubCategory, id=subcategory_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(subcategory=subcategory,
                 quantity=cd['room_quantity'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, subcategory_id):
    cart = Cart(request)
    subcategory = get_object_or_404(RoomSubCategory, id=subcategory_id)
    cart.remove(subcategory)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    username = request.session.get('username', 0)                                                               
    return render(request, 'cart/detail.html', {'cart': cart, 
                                                'username': username,
                                                'categories': categories})

cart/templates/cart/detail.html
{% extends "booking/base.html" %}
{% load static %}
{% block body_block %}

<div class="hero-wrap js-fullheight" style="background-image: url('{% static "booking/images/hotel_background.jpg" %}');">
	<div class="overlay"></div>
	<div class="container">
	<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
		<div class="col-md-9 text-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
			<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="{% url 'booking:index.html' %}">Trang chủ</a></span> <span>Đơn hàng</span></p>
			<h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }" style="font-family:garamond">Đơn hàng</h1>
		</div>
	</div>
	</div>
</div>
<!-- Shopping Cart -->
<div class="shopping-cart section">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<!-- Shopping Summery -->
				<table class="table shopping-summery">
					<thead>
						<tr class="main-hading">
							<th>SẢN PHẨM</th>
							<th>TÊN</th>
							<th class="text-center">ĐƠN GIÁ (đ)</th>
							<th class="text-center">SỐ LƯỢNG</th>
							<th class="text-center">THÀNH TIỀN</th>
							<th class="text-center"><i class="ti-trash remove-icon"></i></th>
						</tr>
					</thead>
					<tbody>
						{% for item in cart %}
						{% with subcategory=item.subcategory %}
						<tr>
							<td class="image" data-title="No"><img src="{{subcategory.image.url}}" alt="{{subcategory.name}}" width="100" height="100">
							</td>
							<td class="product-des" data-title="Description">
								<p class="product-name"><a
										href="{% url 'booking:room_detail.html' subcategory.pk %}">{{subcategory.name}}</a></p>
							</td>
							<td class="price" data-title="Price"><span>{% load humanize %}{{subcategory.default_price|floatformat:0|intcomma}}</span></td>
							<td class="qty" data-title="Qty"><span>{{item.quantity}}</span></td>
							<td class="total-amount" data-title="Total"><span>{% load humanize %}{{item.total_price|floatformat:0|intcomma}}</span></td>
							<td class="action" data-title="Remove">
								<form action="{% url 'cart:cart_remove' subcategory.id %}" method="POST">
									{% csrf_token %}
									<input type="submit" value="&#9746;">
								</form>
							</td>							
						</tr>
						{% endwith %}
						{% endfor %}
					</tbody>
				</table>
				<!--/ End Shopping Summery -->
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<!-- Total Amount -->
				<div class="total-amount">
					<div class="row">
						<div class="col-lg-8 col-md-5 col-12">

						</div>
						<div class="col-lg-4 col-md-7 col-12">
							<div class="right">
								<ul>
									<li class="last">Tổng đơn hàng<span>{% load humanize %}{{cart.get_total_price|floatformat:0|intcomma}} đ</span></li>
								</ul>
								<div class="button5">
									{% if cart %}
									<a href="#" class="btn">Đặt phòng</a>
									{% endif %}
									<a href="{% url 'booking:search_room.html' %}" class="btn">Tiếp tục chọn phòng</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--/ End Total Amount -->
			</div>
		</div>
	</div>
</div>
<!--/ End Shopping Cart -->
{% endblock %}