RiHotel/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from booking import views

router = routers.DefaultRouter()
router.register(r'subcategories', views.RoomSubCategoryViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('dashboard/', include('dashboard.urls')),
]+static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'

urlpatterns = [
    path('', views.index, name='index.html'),
    path('about', views.about, name='about.html'),
    path('room/<int:pk>/', views.room, name='room.html'),
    path('room_detail/<int:pk>/', views.room_detail, name='room_detail.html'),
    path('price_filter', views.filter_by_prices, name='price_filter.html'),
    path('blog', views.read_feeds, name='blog.html'),
    path('contact', views.contact, name='contact.html'),
    path('subscribe', views.subscribe, name='subscribe.html'),
    path('register', views.register, name='register.html'),
    path('login', views.log_in, name='login.html'),
    path('logout', views.log_out, name='logout.html'),
    path('search_room', views.search_room, name='search_room.html'),
    path('subcategories', views.read_subcategories, name='subcategories.html'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:subcategory_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:subcategory_id>/', views.cart_remove, name='cart_remove'),
]

booking/forms.py
from django import forms
from . import models
from django.core.validators import RegexValidator


class SearchRoom(forms.Form):
    checkin_date = forms.DateField()
    checkout_date = forms.DateField()
    category_id = forms.IntegerField()

phone_validator = RegexValidator(
    r"((\([0-9]{3}\)[0-9]{9,15})|([0-9]{10,15}))", "Your phone number should be (xxx)xxxxxxxxx or 0xxxxxxxxx")

class FormContact(forms.ModelForm):
    name = forms.CharField(max_length=150, widget=forms.TextInput(attrs={
                           'class': 'form-control fh5co_contact_text_box'}))
    phone= forms.CharField(max_length=20, validators=[phone_validator], widget=forms.TextInput(
        attrs={
               'class': 'form-control fh5co_contact_text_box',
               'pattern': '((\([0-9]{3}\)[0-9]{9,15})|([0-9]{10,15}))',
               'title': 'Your phone number should be (xxx)xxxxxxxxx or 0xxxxxxxxx'}))
    email = forms.EmailField(label='Email', widget=forms.TextInput(
        attrs={'class': 'form-control fh5co_contact_text_box'}))
    subject = forms.CharField(label='Subject', widget=forms.TextInput(
        attrs={'class': 'form-control fh5co_contact_text_box'}))
    message = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control fh5co_contacts_message'}))

    class Meta:
        model = models.Contact
        fields = '__all__'

class UserForm(forms.ModelForm):
    password = forms.CharField(max_length=150, widget=forms.PasswordInput())
    confirm = forms.CharField(max_length=150, widget=forms.PasswordInput())   

    class Meta():
        model = models.User
        fields = ('username', 'email', 'password', 'first_name', 'last_name')

class UserProfileInfoForm(forms.ModelForm):
    phone = forms.CharField(max_length=20, validators=[phone_validator])

    class Meta():
        model = models.UserProfileInfo
        exclude = ('user', )

booking/views.py
from operator import sub
import re
from django.http import HttpResponse
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, F, Value
from RiHotel.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from . import models
from . import forms
import datetime
import feedparser
import json
import urllib.request

DEFAULT_ENCODING = 'utf-8'

# rest_framework
from rest_framework import viewsets
from rest_framework import permissions
from .serializers import RoomSubCategorySerializer, RoomCategorySerializer

from cart.cart import Cart
from django.template.defaulttags import register





# Create your views here.

@register.filter
def get_item(dictionary, key):
    return dictionary and dictionary.get(key) or None

categories = models.RoomCategory.objects.order_by("-average_area")

def index(request):
    subcategory_list = models.RoomSubCategory.objects.all()
    username = request.session.get('username', 0)
    
    return render(request, 'booking/index.html',
                {
                    'subcategory_list': subcategory_list,
                    'categories': categories,
                    'username': username,
                })

def about(request):
    username = request.session.get('username', 0)
    return render(request, 'booking/about.html',
                {
                    'categories': categories,
                    'username': username,
                })

def room(request, pk):
    subcategory_list = []
    if pk != 0:
        subcategory_list = models.RoomSubCategory.objects.filter(
            category_id=pk)
    else:
        subcategory_list = models.RoomSubCategory.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(subcategory_list, 9)
    try:
        rooms = paginator.page(page)
    except PageNotAnInteger:
        rooms = paginator.page(1)
    except EmptyPage:
        rooms = paginator.page(paginator.num_pages)
    
    username = request.session.get('username', 0)
    
    return render(request, 'booking/room.html',
                {
                    'subcategory_list': subcategory_list,
                    'categories': categories,
                    'rooms': rooms,
                    'pk': pk,
                    'username': username,
                })

def room_detail(request, pk):
    selected_room = models.RoomSubCategory.objects.get(pk=pk)
    models.RoomSubCategory.objects.filter(pk=selected_room.pk).update(viewed=F('viewed')+1)
    selected_room.refresh_from_db()

    subcategory_list = models.RoomSubCategory.objects.all()
    
    username = request.session.get('username', 0)

    return render(request, 'booking/room_detail.html',
                            {
                                'subcategory_list': subcategory_list,
                                'selected_room': selected_room,
                                'pk': pk,
                                'categories': categories,
                                'username': username,
                            })

def blog(request):
    username = request.session.get('username', 0)
    return render(request, 'booking/blog.html',
                {
                    'categories': categories,
                    'username': username,
                })

def contact(request):
    username = request.session.get('username', 0)
    return render(request, 'booking/contact.html',
                    {
                        'categories': categories,
                        'username': username,
                    })

def search_room(request):
    global checkin_date
    global checkout_date
    global category_id

    subcategory_list = []

    if request.method == 'GET':
        form = forms.SearchRoom(request.GET)
        if form.is_valid():
            checkin_date = form.cleaned_data.get('checkin_date')
            checkout_date = form.cleaned_data.get('checkout_date')
            category_id = form.cleaned_data.get('category_id')

            if category_id != 0:
                category = models.RoomCategory.objects.get(pk=category_id)
                for room in category.get_available_rooms(checkin_date, checkout_date):
                    if room.subcategory_id not in subcategory_list:
                        subcategory_list.append(room.subcategory_id)
            else:
                all_category = models.RoomCategory.objects.all()
                for category in all_category:
                    for room in category.get_available_rooms(checkin_date, checkout_date):
                        if room.subcategory_id not in subcategory_list:
                            subcategory_list.append(room.subcategory_id)
    total_room = {}
    for subcategory in subcategory_list:
        room_list = []
        for room in models.Room.objects.filter(subcategory_id=subcategory.id):
            room_list.append(room)
            total_room[subcategory.id] = len(room_list)
    
    username = request.session.get('username', 0)

    print(Cart(request).cart)
    return render(request, 'booking/search_room.html',
                {
                    'total_room': total_room,
                    'categories': categories,
                    'subcategory_list': subcategory_list,
                    'checkin_date': checkin_date,
                    'checkout_date': checkout_date,
                    'username': username,
                    'cart': Cart(request).cart,
                })

def filter_by_prices(request):
    username = request.session.get('username', 0)
    global category_id
    if request.method == 'GET':
        category_id = request.GET.get('category_id')
        a = float(request.GET.get('price_from'))
        b = float(request.GET.get('price_to'))
        price_from = a
        price_to = b
        if(a > b):
            price_from = b
            price_to = a

    if category_id != "0":
        subcategory_list = models.RoomSubCategory.objects.filter(category_id=category_id)
    else:
        subcategory_list = models.RoomSubCategory.objects.all()

    subcategory_list = [subcategory for subcategory in subcategory_list if subcategory.default_price >=
                    price_from and subcategory.default_price <= price_to]

    return render(request, "booking/room.html",
                    {
                    'categories': categories,
                    'category_id': category_id,
                    'subcategory_list': subcategory_list,
                    'username': username,
                    })

def contact(request):
    result = ''
    form = forms.FormContact()

    if request.method == 'POST':
        result='Form POST'
        form = forms.FormContact(request.POST, models.Contact)
        result='Form Contatct'
        if form.is_valid():
            request.POST._mutable = True
            post = form.save(commit=False)
            post.name = form.cleaned_data['name']
            post.phone = form.cleaned_data['phone']
            post.email = form.cleaned_data['email']
            post.password = form.cleaned_data['subject']
            post.password = form.cleaned_data['message']
            post.save()
            result = "Cảm ơn quý khách đã liên hệ. Chúng tôi sẽ phản hồi trong thời gian sớm nhất."
    else:
        form = forms.FormContact()

    username = request.session.get('username', 0)
    
    return render(request, "booking/contact.html",
                  {
                   'form': form,
                   'result': result,
                   'categories': categories,
                   'username': username,
                   })

def subscribe(request):
    username = request.session.get('username', 0)
    if request.method == 'POST':
        email_address = request.POST.get("email")
        subject = 'Lời chào từ Ri Hotel'
        message = 'Hy vọng các thông tin ở đây sẽ giúp quý khách có một kỳ nghỉ tuyệt vời.'
        recepient = str(email_address)

        html_content = '<h2 style="color:blue"><i>Kính chào quý khách,</i></h2>'\
            + '<p>Cảm ơn quý khách đã ghé thăm website của <strong>Ri Hotel</strong>.</p>' \
            + '<p>' + message + '</p>'

        msg = EmailMultiAlternatives(
            subject, message, 'Ri Hotel <betrueri1123@gmail.com', [recepient])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        # send_mail(subject, message, EMAIL_HOST_USER,
        #           [recepient], fail_silently=False)

        result = "Email từ Ri Hotel đã được gửi đến hộp thư của quý khách. Xin cảm ơn."

        return render(request, 'booking/base.html', {
                                                     'result': result,
                                                     'categories': categories,
                                                     'username': username,
                                                     })
    
    return render(request, 'booking/base.html',{
                                                'categories': categories,
                                                'username': username,
                                                })

def read_feeds(request):
    news_feed = feedparser.parse("https://hellodulich.com/feed/")
    entry = news_feed.entries
    
    username = request.session.get('username', 0)
    
    return render(request, 'booking/blog.html', {
                                                'feeds': entry,
                                                'categories': categories,
                                                'username': username,
                                                })

def register(request):
    registered = False
    if request.method == "POST":
        form_user = forms.UserForm(data=request.POST)

booking/templates/booking/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
	<head>
		<title>Ri Hotel</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
		<link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">

		<link rel="stylesheet" href='{% static "booking/css/open-iconic-bootstrap.min.css" %}'>
		<link rel="stylesheet" href='{% static "booking/css/animate.css" %}'>
		
		<link rel="stylesheet" href='{% static "booking/css/owl.carousel.min.css" %}'>
		<link rel="stylesheet" href='{% static "booking/css/owl.theme.default.min.css" %}'>
		<link rel="stylesheet" href='{% static "booking/css/magnific-popup.css" %}'>

		<link rel="stylesheet" href='{% static "booking/css/aos.css" %}'>

		<link rel="stylesheet" href='{% static "booking/css/ionicons.min.css" %}'>

		<link rel="stylesheet" href='{% static "booking/css/bootstrap-datepicker.css" %}'>
		<link rel="stylesheet" href='{% static "booking/css/jquery.timepicker.css" %}'>

		<link rel="stylesheet" href='{% static "booking/css/flaticon.css" %}'>
		<link rel="stylesheet" href='{% static "booking/css/icomoon.css" %}'>
		<link rel="stylesheet" href='{% static "booking/css/style.css" %}'>
	</head>
	

	<body>

		<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
			<div class="container">
				<div class="collapse navbar-collapse" id="ftco-nav">
					<ul class="navbar-nav ml-auto">
						{% if username %}
						<p style="color:black">{{username}}</p>
						<li class="nav-item"><a href="{% url 'booking:logout.html'%}" class="nav-link">Đăng xuất</a></li>
						{% else %}
						<li class="nav-item"><a href="{% url 'booking:register.html'%}" class="nav-link">Đăng ký</a></li>
						<li class="nav-item"><a href="{% url 'booking:login.html'%}" class="nav-link">Đăng nhập</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
			<div class="container">
				<div class="collapse navbar-collapse" id="ftco-nav">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item"><a href="{% url 'booking:index.html' %}" class="nav-link">Trang chủ</a></li>
						<li class="nav-item"><a href="{% url 'booking:about.html' %}" class="nav-link">Giới thiệu</a></li>
						<li class="nav-item dropdown">
							<a role="button" data-bs-toggle="dropdown" aria-expanded="false" href="{% url 'booking:room.html' 0%}" class="nav-link dropdown-toggle">Phòng</a>
									<ul class="dropdown-menu">
										{% for category in categories %}
											<li><a class="dropdown-item" href="{% url 'booking:room.html' category.id %}">{{category.name}}</a></li>
										{% endfor %}
									</ul>
						</li>
						<li class="nav-item"><a href="{% url 'booking:blog.html' %}" class="nav-link">Blog</a></li>
						<li class="nav-item"><a href="{% url 'booking:contact.html' %}" class="nav-link">Liên hệ</a></li>
						<li class="nav-item"><a href="{% url 'cart:cart_detail' %}" class="nav-link">Đơn hàng</a></li>
					</ul>
				</div>
			</div>
		</nav>

		{% block body_block %}
		{% endblock %}

		<section class="ftco-section-parallax">
			<div class="parallax-img d-flex align-items-center">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
							<h2 style="font-family:Cambria, Cochin, Georgia, Times, 'Times New Roman', serif">Theo dõi các thông tin của Ri Hotel</h2>
							<!-- <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p> -->
							<div class="row d-flex justify-content-center mt-5">
								<div class="col-md-8">
									<form action="{% url 'booking:subscribe.html' %}" class="subscribe-form" method="POST">
										{% csrf_token %}
										<div class="form-group d-flex">
											<input type="email" class="form-control" placeholder="Email" name="email">
											<input type="submit" value="Đăng ký" class="submit px-3">
										</div>
									</form>
								</div>
								<div class="row d-flex justify-content-center mt-5">
									<h6 style="font-family:fantasy; color: black; font-size: 20px;">{{result}}</h6>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		
		<footer class="ftco-footer ftco-bg-dark ftco-section" style="background:#000000; padding: 5em 0">
		<div class="container">
			<div class="row mb-5">
			<div class="col-md">
				<div class="ftco-footer-widget mb-4">
				<h2 class="ftco-heading-2" style="font-size:50px; font-weight:bold; color:#ffffff">Ri Hotel</h2>
				<p>Khách sạn cung cấp dịch vụ lưu trú trên toàn quốc</p>
				<ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
					<li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
					<li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
					<li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
				</ul>
				</div>
			</div>
			<div class="col-md">
				<div class="ftco-footer-widget mb-4 ml-md-4">
				<h2 class="ftco-heading-2">Thông tin</h2>
				<ul class="list-unstyled">
					<li><a href="{% url 'booking:about.html' %}" class="py-2 d-block">Giới thiệu</a></li>
					<li><a href="{% url 'booking:contact.html' %}" class="py-2 d-block">Liên hệ</a></li>
					<li><a href="#" class="py-2 d-block">Chính sách và điều khoản</a></li>
					<li><a href="#" class="py-2 d-block">Quy định đặt phòng</a></li>
					<li><a href="#" class="py-2 d-block">Hoàn tiền</a></li>
				</ul>
				</div>
			</div>
			<div class="col-md">
				<div class="ftco-footer-widget mb-4">
					<h2 class="ftco-heading-2">Liên hệ</h2>
					<div class="block-23 mb-3">
					<ul>
						<li><span class="icon icon-map-marker"></span><span class="text">6A Quân Trấn, phường Lộc Thọ, Nha Trang, Khánh Hòa</span></li>
						<li><a href="#"><span class="icon icon-phone"></span><span class="text">(0258) 3870177</span></a></li>
						<li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@rihotel.com</span></a></li>
					</ul>
					</div>
				</div>
			</div>
			</div>
			<div class="row">
			<div class="col-md-12 text-center">

				<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
	Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
	<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
			</div>
			</div>
		</div>
		</footer>

  	<!-- loader -->
	<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

	<script src='{% static "booking/js/jquery.min.js" %}'></script>
	<script src='{% static "booking/js/jquery-migrate-3.0.1.min.js" %}'></script>
	<script src='{% static "booking/js/popper.min.js" %}'></script>
	<script src='{% static "booking/js/bootstrap.min.js" %}'></script>
	<script src='{% static "booking/js/jquery.easing.1.3.js" %}'></script>
	<script src='{% static "booking/js/jquery.waypoints.min.js" %}'></script>
	<script src='{% static "booking/js/jquery.stellar.min.js" %}'></script>
	<script src='{% static "booking/js/owl.carousel.min.js" %}'></script>
	<script src='{% static "booking/js/jquery.magnific-popup.min.js" %}'></script>
	<script src='{% static "booking/js/aos.js" %}'></script>
	<script src='{% static "booking/js/jquery.animateNumber.min.js" %}'></script>
	<script src='{% static "booking/js/bootstrap-datepicker.js" %}'></script>
	<script src='{% static "booking/js/jquery.timepicker.min.js" %}'></script>
	<script src='{% static "booking/js/scrollax.min.js" %}'></script>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
	<script src='{% static "booking/js/google-map.js" %}'></script>
	<script src='{% static "booking/js/main.js" %}'></script>

	</body>
</html>

booking/templates/booking/blog.html
{% extends "booking/base.html" %}
{% load static %}
{% block body_block %}

<div class="hero-wrap js-fullheight" style="background-image: url('{% static "booking/images/hotel_background.jpg" %}');">
	<div class="overlay"></div>
	<div class="container">
	<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
		<div class="col-md-9 text-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
			<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="{% url 'booking:index.html' %}">Trang chủ</a></span> <span>Blog</span></p>
			<h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }" style="font-family:garamond">Các gợi ý &amp; Bài viết</h1>
		</div>
	</div>
	</div>
</div>

<section class="ftco-section bg-light">
	<div class="container">
		<div class="contact-head">			
			<div class="col-12">
				<div class="section-title">
					<h2>HELLO DU LỊCH VIỆT NAM</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12 col-12">
					<table class="table">
						{% for entry in feeds %}
						<tr>
							<td>
								<h5><a href="{{entry.link}}" style="color:#23706a"> {{entry.title}} </a></h5>
								<i><a href="{{entry.link}}" style="color:#23706a">{{entry.published}} </a></i>
								<div>{{entry.description|safe}}</div>
							</td>					
						</tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

booking/templates/booking/search_room.html
{% extends "booking/base.html" %}
{% load static %}
{% block body_block %}

<div class="hero-wrap js-fullheight" style="background-image: url('{% static "booking/images/hotel_background.jpg" %}');">
	<div class="overlay"></div>
	<div class="container">
	<div class="row no-gutters slider-text js-fullheight align-items-center justify-content-center" data-scrollax-parent="true">
		<div class="col-md-9 text-center ftco-animate" data-scrollax=" properties: { translateY: '70%' }">
			<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-2"><a href="{% url 'booking:index.html' %}">Trang chủ</a></span> <span>Phòng</span></p>
			<h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }" style="font-family:garamond">Phòng lưu trú</h1>
		</div>
	</div>
	</div>
</div>

<section class="ftco-section">
	<div class="container">
	<div class="row">
		<div class="col-lg-12">
		<div class="row">
			{% for subcategory in subcategory_list %}
				<div class="col-sm col-md-6 col-lg-6 ftco-animate">
					<div class="destination">
						<a href="{% url 'booking:room_detail.html' subcategory.pk %}" class="img img-2 d-flex justify-content-center align-items-center"
							style="background-image: url('{{subcategory.image.url}}')">
						</a>
						<div class="text p-3">
							<div class="d-flex">
								<div class="one">
									<h3><a  class="text-nowrap" href="{% url 'booking:room_detail.html' subcategory.pk %}">{{subcategory.name}}</a></h3>
									<p class="rate">
										<i class="icon-star"></i>
										<i class="icon-star"></i>
										<i class="icon-star"></i>
										<i class="icon-star"></i>
										<i class="icon-star-o"></i>
										<span>8 Rating</span>
									</p>
								</div>
								<div class="two">
									<span class="price per-price">{% load humanize %}{{subcategory.default_price|floatformat:0|intcomma}}<br><small>/đêm</small></span>
								</div>
							</div>
							<span style="font-family:'Times New Roman', Times, serif">Diện tích: {% load humanize %}{{subcategory.default_area|floatformat:0|intcomma}} m<sup>2</sup></span>
							<p style="font-family:'Times New Roman', Times, serif">Sức chứa tối đa: {{subcategory.default_capacity}} người</p>
							<hr>
							<p class="bottom-area d-flex">
								<form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'cart:cart_add' subcategory.id %}" method="POST">
									{% csrf_token %}
									<div class="col-md-3">
									  <label for="inlineFormInputGroupUsername">Số phòng</label>
									  {% for key, value in total_room.items %}
									  {% if key == subcategory.id %}
									  <span class="input-group">
										<input type="number" class="form-control" id="inlineFormInputGroupUsername"
											min="0" max="{{value}}" value="" name="room_quantity">
									  </span>
									  {% endif %}
									  {% endfor %}
									</div>
								  
									<div class="col-md-3">
									  <label for="inlineFormSelectPref">Số khách</label>
									  <div class="input-group">
										<input type="number" class="form-control" id="inlineFormInputGroupUsername"
										min="0" value="{{count_guests}}" name="count_guests">
									  </div>
									</div>
								  
									<div class="col-md-6">
									  <button type="submit" class="btn btn-primary">Thêm vào giỏ hàng</button>
									</div>
								</form>
							</p>
						</div>
					</div>
				</div>

			{% endfor %}
		</div>
		</div>
	</div>
	</div>
</section> 

{% endblock %}