RiHotel/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from booking import views

router = routers.DefaultRouter()
router.register(r'subcategories', views.RoomSubCategoryViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('dashboard/', include('dashboard.urls')),
]+static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:subcategory_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:subcategory_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

orders/models.py
from django.db import models

# Create your models here.

# from booking.models import Room, RoomSubCategory


class Order(models.Model):
    username = models.CharField(max_length=50, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=20, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    checkin_date = models.DateField()
    checkout_date = models.DateField()
    state = models.CharField(max_length=20,
        choices=[
            ('draft','Draft'),
            ('confirmed', 'Confirmed'),
            ('checked_in', 'Checked In'),
            ('checked_out', 'Checked Out'),
            ('done', 'Done'),
            ('cancel', 'Cancel')
        ])

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    room = models.ForeignKey(Room,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    phone = forms.CharField(max_length=20, label='Phone', widget=forms.TextInput(
        attrs={'pattern': '((\([0-9]{3}\)[0-9]{9,15})|([0-9]{10,15}))',
               'title': 'Your phone number must be (xxx)xxxxxxxxx or 0xxxxxxxxx'}))
    class Meta:
        model = Order
        fields = ['username', 'first_name', 'last_name', 'address', 'phone']

orders/views.py
from django.shortcuts import render

# Create your views here.
from cart.cart import Cart
from .models import OrderItem, Order
from .forms import OrderCreateForm
#from .tasks import order_created
from booking import models

# thư viện cho việc sử dụng email
from RiHotel.settings import EMAIL_HOST_USER
from django.core.mail import send_mail

from django.core.mail import EmailMultiAlternatives


subcategory_list = models.SubCategory.objects.all()


def order_create(request):
    cart = Cart(request)
    username = request.session.get('username', 0)
    if username:
        user = models.User.objects.get(username=username)
        user_profile = models.UserProfileInfo.objects.get(user=user)
        order = Order()
        order.username = user.username
        order.first_name = user.first_name
        order.last_name = user.last_name
        order.email = user.email
        order.phone = user_profile.phone
        order.address = user_profile.address
    else:
        order = Order()

    if request.method == 'POST':
        form = OrderCreateForm(request.POST, order)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])

            # Gửi email
            email_address = form.cleaned_data['email']
            subject = 'Xác nhận đơn hàng ' + str(order.id)
            message = 'Cảm ơn quý khách <b>' + order.last_name + \
                ' ' + order.first_name + '</b> đã đặt phòng tại RiHotel,'
            recepient = str(email_address)

            html_content = '''
            <p style="margin:4px 0;font-family:Arial, Helvetica, sans-serif;font-size:12px;color:#444;line-height:18px;font-weight:normal;">My Store rất vui thông báo đơn hàng ''' + \
                str(order.id) + \
                ''' của quý khách đã được tiếp nhận và đang trong quá trình xử lý. </p>									
			<h3 style="font-size:13px;font-weight:bold;color:#02acea;text-transform:uppercase;margin:20px 0 0 0;border-bottom:1px solid #ddd;">Thông tin đơn hàng:</h3>''' + \
                '''<h5>Họ và tên: ''' + \
                order.last_name + \
                ''' ''' + \
                order.first_name + \
                '''</h5> ''' + \
                '<h5>Phone: ' + \
                str(order.phone) + \
                '''</h5> ''' + \
                '''<h2 style="text-align:left;margin:10px 0;border-bottom:1px solid #ddd;padding-bottom:5px;font-size:13px;color:#02acea;">CHI TIẾT ĐƠN HÀNG</h2>''' + \
                '''<table border="0" cellpadding="0" cellspacing="0" style="background:#f5f5f5;" width="100%">''' + \
                ''' <thead>
											<tr>
												<th align="left" bgcolor="#02acea" style="padding:6px 9px;color:#fff;font-family:Arial, Helvetica, sans-serif;font-size:12px;line-height:14px;">Sản phẩm</th>
												<th align="left" bgcolor="#02acea" style="padding:6px 9px;color:#fff;font-family:Arial, Helvetica, sans-serif;font-size:12px;line-height:14px;">Đơn giá</th>
												<th align="left" bgcolor="#02acea" style="padding:6px 9px;color:#fff;font-family:Arial, Helvetica, sans-serif;font-size:12px;line-height:14px;">Số lượng</th>
												<th align="right" bgcolor="#02acea" style="padding:6px 9px;color:#fff;font-family:Arial, Helvetica, sans-serif;font-size:12px;line-height:14px;">Tổng tạm</th>
											</tr>
										</thead>
                                        <tbody style="font-family:Arial, Helvetica, sans-serif;font-size:12px;color:#444;line-height:18px;">
            '''
            for item in cart:
                html_content += '''
                <tr>
					<td align="left" style="padding:3px 9px;" valign="top"><span class="yiv1530170030name">''' + \
                    str(item['product']) + \
                    '''</td>''' + \
                    '''<td align="left" style="padding:3px 9px;" valign="top"><span>''' + \
                    str("{:0,.0f}".format(item['price'])) + \
                    '''</span></td>''' + \
                    ''' <td align="left" style="padding:3px 9px;" valign="top">''' + \
                    str(item['quantity']) + \
                    '''</td>''' + \
                    '''<td align="right" style="padding:3px 9px;" valign="top"><span>''' + \
                    str("{:0,.0f}".format(item['total_price'])) + \
                    '''</span></td></tr>'''
            html_content += '''<tr><td colspan="4" style="text-align:right">Tổng đơn hàng:''' + \
                str("{:0,.0f}".format(cart.get_total_price())) + \
                '''đ</td></tr>'''
            html_content += '''</table>

            <p style="margin:0;font-family:Arial, Helvetica, sans-serif;font-size:12px;color:#444;line-height:18px;font-weight:normal;">Trường hợp quý khách có những băn khoăn về đơn hàng, có thể liên hệ với chúng tôi theo số <b>(028) 38 351 056</b></p>'''

            msg = EmailMultiAlternatives(
                subject, message, EMAIL_HOST_USER, [recepient])
            msg.attach_alternative(html_content, "text/html")
            msg.send()

            # clear the cart
            cart.clear()

            return render(request,
                          'orders/order/created.html',
                          {'order': order, 'subcategories': subcategory_list, 'username': username})
    else:
        form = OrderCreateForm(instance=order)
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form, 'subcategories': subcategory_list, 'username': username})

orders/templates/orders/order/create.html
{% extends "booking/base.html" %}
{% load static %}
{% block body_block %}

<!-- Start Checkout -->
<section class="shop checkout section">
	<div class="container">
		<form class="form" method="POST" action="{% url 'orders:order_create'%}">
		<div class="row">
			<!-- Form -->
			<div class="col-lg-8 col-12">
				<div class="checkout-form">
					<h2>Thông tin khách hàng</h2>
					<p>Vui lòng đăng ký tài khoản tại <a href="{% url 'booking:register.html'%}">
						<b>Đăng ký</b></a> để việc đặt hàng nhanh chóng và dễ dàng hơn</p>
					<div class="row">
						<div class="col-lg-6 col-md-6 col-12">
							<div class="form-group">
								<input type="hidden" value="{{username}}" name="username"/>
								<label>Họ<span>*</span></label>
								{{form.last_name}}
							</div>
						</div>

						<div class="col-lg-6 col-md-6 col-12">
							<div class="form-group">
								<label>Tên<span>*</span></label>
								{{form.first_name}}
							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-12">
							<div class="form-group">
								<label>Email<span>*</span></label>
								{{form.email}}
							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-12">
							<div class="form-group">
								<label>Số điện thoại<span>*</span></label>
								{{form.phone}}
							</div>
						</div>
					</div>					
				</div>
			</div>
			<div class="col-lg-4 col-12">
				<div class="order-details">
					<!-- Order Widget -->
					<div class="single-widget">
						<h2>THÔNG TIN GIỎ HÀNG</h2>
						<div class="content">
							<ul>
								{% for item in cart %}
								<li>
									{{ item.quantity }}x {{ item.product.name }}
									<span>{% load humanize %}{{item.total_price|floatformat:0|intcomma}} đ</span>
								</li>
								{% endfor %}
							</ul>
							<ul>
								<li>
									<hr />
								</li>
								<li>Tạm tính<span>{% load humanize %}{{cart.get_total_price|floatformat:0|intcomma}} đ</span></li>
								<li>(+) Giao hàng<span>0 đ</span></li>
								<li class="last">Tổng đơn hàng<span>{% load humanize %}{{cart.get_total_price|floatformat:0|intcomma}} đ</span></li>
							</ul>
						</div>
					</div>
					<!--/ End Order Widget -->
					<!-- Button Widget -->
					<div class="single-widget get-button">
						<div class="content">
							<div class="button">
								<button type="submit" class="btn ">Đặt hàng</button>
								{% csrf_token %}
							</div>
						</div>
					</div>
					<!--/ End Button Widget -->
				</div>
			</div>
		</div>		
		</form>
		<!--/ End Form -->
	</div>
</section>
<!--/ End Checkout -->

{% endblock %}

orders/templates/orders/order/created.html
{% extends "booking/base.html" %}
{% load static %}
{% block body_block %}

<!-- Start Checkout -->
<section class="shop checkout section">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-12">
				<div class="checkout-form">
					<h2>Cảm ơn quý khách</h2>
					<p>Quý khách <b> {{order.last_name}} {{order.first_name}} </b> đã đặt hàng thành công. Đơn hàng của quý khách
						có mã số {{order.id }}</p>
				</div>
			</div>
			<div class="col-lg-4 col-12">
				<div class="order-details">
					<!-- Order Widget -->
					<div class="single-widget">
						<h2>THÔNG TIN GIAO HÀNG (Dự kiến)</h2>
						<div class="content">
							<ul>
								<li>Phone: {{order.phone}}</li>
								<li>Email: {{order.email}}</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!--/ End Checkout -->

{% endblock %}