RiHotel/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from booking import views

router = routers.DefaultRouter()
router.register(r'subcategories', views.RoomSubCategoryViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('dashboard/', include('dashboard.urls')),
]+static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:subcategory_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:subcategory_id>/', views.cart_remove, name='cart_remove'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_with_pivot, name='dashboard_with_pivot'),
    path('data', views.pivot_data, name='pivot_data'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.http import JsonResponse
from booking.models import RoomSubCategory, Room, RoomCategory
from django.core import serializers

# Create your views here.
def dashboard_with_pivot(request):
    return render(request, 'dashboard/dashboard_with_pivot.html', {})

def pivot_data(request):
    dataset = RoomSubCategory.objects.all()
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)

dashboard/templates/dashboard/dashboard_with_pivot.html
<head>
    <meta charset="UTF-8">
    <title>Dashboard with Flexmonster</title>
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
</head>

<body>
    <div id="pivot-table-container" data-url="{% url 'dashboard:pivot_data' %}"></div>
    <div id="pivot-chart-container"></div>
    <div id="pivot-chart-container2"></div>
    <script>
        function processData(dataset) {
            var result = []
            dataset = JSON.parse(dataset);
            dataset.forEach(item => result.push(item.fields));
            return result;
        }
        $.ajax({
            url: $("#pivot-table-container").attr("data-url"),
            dataType: 'json',
            success: function (data) {
                new Flexmonster({
                    container: "#pivot-table-container",
                    componentFolder: "https://cdn.flexmonster.com/",
                    width: "100%",
                    height: 430,
                    toolbar: true,
                    report: {
                        dataSource: {
                            type: "json",
                            data: processData(data),
                        },
                        slice: {}
                    }
                });
                new Flexmonster({
                    container: "#pivot-chart-container",
                    componentFolder: "https://cdn.flexmonster.com/",
                    width: "100%",
                    height: 430,
                    //toolbar: true,
                    report: {
                        dataSource: {
                            type: "json",
                            data: processData(data)
                        },
                        slice: {},
                        "options": {
                            "viewType": "charts",
                            "chart": {
                                "type": "pie"
                            }
                        }
                    }
                });
            }
        });
    </script>
</body>